### ISSUE TITLE
Language is changed

### ISSUE THREAD

**Issue by 732592864** [aki-art/ONI-Mods#14]
When the module is started, the game settings of the new map are changed and forced into English
![image](https://user-images.githubusercontent.com/68160649/193529021-01583727-4c8d-456e-a228-03db937557e4.png)
The following is before startup
![image](https://user-images.githubusercontent.com/68160649/193528853-b88680ad-4de9-4700-a6a2-5c8b5c85bf38.png)

**Comment by aki-art** [comment]
None of my mods affect that screen or anything near it. Are you sure it's one of my mods?
And which mod are you referring to?

**Comment by 732592864** [comment]
I'm glad you saw my message

I'm sure it's your module, because I found your contact information from Steam Creative Workshop

The second module that causes this problem is

True Tiles (texture mod)

For this module, I closed all other modules and tried again. The problem remains

After the ontology and DLC are started, the new game setting language will be forced English
![image](https://user-images.githubusercontent.com/68160649/193775351-7ad290ad-ffe4-4918-9268-c180c7979a0e.png)

**Comment by aki-art** [comment]
Thank you for the report. 

Found the issue. Turns out tweaking the main `Game` class by the usual modding methods, some dialogs will be forced to load before localizations are loaded, that means it can only access english strings. Multiple mods have this same issue by other authors as well.

Fix will come soon to True Tiles and also Bio-Inks.

**Comment by aki-art** [comment]
Fixed in the last update

**Comment by 732592864** [comment]
thanks
